### ISSUE TITLE
{BOT} test milestone

### ISSUE THREAD

**Issue by wangzelin007** [wangzelin007/github-bot-tutorial#34]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by wangzelin007** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin007** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin007** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin007** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
TEST

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!
