### ISSUE TITLE
{BOT} Test milestone

### ISSUE THREAD

**Issue by wangzelin007** [wangzelin007/github-bot-tutorial#36]
If the issue creation time is less than 21 days, put into the next milestone and notify the user.

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone
