### ISSUE TITLE
{DEMO} Test auto reply and set milestone

### ISSUE THREAD

**Issue by wangzelin007** [wangzelin007/github-bot-tutorial#39]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone
