### ISSUE TITLE
{feature request}

### ISSUE THREAD

**Issue by wangzelin007** [wangzelin007/github-bot-tutorial#49]
### Related command

None

### Resource Provider

None

### Description of Feature or Work Requested

None

### Minimum API Version Required

None

### Swagger PR link / SDK link

None

### Request Example

None

### Target Date

None

### Additional context

None

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!

**Comment by wangzelin008** [comment]
Hi @wangzelin007, Since the current milestone time is less than 21 days, this issue will be resolved in the next milestone
