### ISSUE TITLE
az sig image-version create --tags break in version 2.38.0-1

### ISSUE THREAD

**Issue by wangzelin007** [wangzelin007/github-bot-tutorial#96]
Install latest version Azure CLI on ubuntu 1804
run az sig image-version create .... --tags test=true encounter this error  Parameter 'tags' must be of type 'dict[str, str]', downgrade version into 2.37.0-1, it works well.

**Comment by wangzelin008** [comment]
Thanks for the report @wangzelin007! We will look into it ASAP!
